baseURL       = "/"
languageCode  = "pl-pl"
title         = "Położna | mgr Kamila Łabędź"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus

  [[menu.nav]]
    name    = "O mnie"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Oferta"
    url     = "oferta"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3

  [[menu.nav]]
    name    = "Wydarzenia"
    url     = "portfolio"
    weight  = 4
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 5

 
# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Położna | Kamila Łabędź"
  author = "Kamila Łabędź"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png"
    heading               = ""
    tagline               = ""
    primary_button        = "Facebook"
    primary_button_url    = "https://www.facebook.com/midwife.talks"
    secondary_button      = "Instagram"
    secondary_button_url  = "https://www.instagram.com/midwife.talks/"
  [params.portfolio]
    enable    = true
    title     = "Wydarzenia:"


  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Dużo ciekawych informacji znajdziesz również na prowadzonych przeze mnie profilach:"
    primary_button      = "Facebook"
    primary_button_url  = "https://www.facebook.com/midwife.talks"
    secondary_button    = "Instagram"
    secondary_button_url = "https://www.instagram.com/midwife.talks/"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informacje kontaktowe"
      phone   = "+48609877544"
      email   = "kamila.labedz@outlook.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Mapa strony"
        [[params.footer.sitemap.link]]
          name = "O mnie"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Oferta"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Kontakt"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/midwife.talks"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/midwife.talks/"
